GET http://localhost:8080/api/flowers/list

###
POST http://localhost:8080/api/flowers/add
Content-Type: application/json

{
  "id": 2,
  "flowerType": 0,
  "sepalLength": 0.8,
  "color": 0,
  "price": 343
}